# Generated by Django 5.2.5 on 2025-08-18 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, help_text='Apenas dígitos', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Informe apenas dígitos.', regex='^\\d+$')])),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11,14}$', 'CPF/CNPJ deve conter 11 a 14 dígitos.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['nome'], name='clientes_cl_nome_b2cdde_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf_cnpj__isnull', True)), fields=('nome', 'email'), name='uniq_cliente_nome_email_when_no_doc')],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_completo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cliente', 'endereco_completo'), name='uniq_endereco_por_cliente')],
            },
        ),
    ]
