# Generated by Django 5.2.5 on 2025-08-18 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF/CNPJ deve conter de 11 a 14 dígitos.', regex='^\\d{11,14}$')]),
        ),
    ]
