# Generated by Django 5.2.5 on 2025-08-18 19:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_mensagem', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='produtos.produto')),
            ],
            options={
                'indexes': [models.Index(fields=['data_hora'], name='vendas_comp_data_ho_d38eee_idx'), models.Index(fields=['produto', 'data_hora'], name='vendas_comp_produto_689479_idx'), models.Index(fields=['cliente', 'data_hora'], name='vendas_comp_cliente_9b7da1_idx')],
            },
        ),
    ]
